//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadTools.TypedScenes
{
    using UnityEngine;
    using UnityEngine.SceneManagement;
    using LeadTools.StateMachine;
    
    
    public class Level_51 : TypedScene<GameStateMachine>
    {
        
        private const string _sceneName = "Level_51";
        
        public static void Load<T>(T argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        
        {
            LoadScene<T>(_sceneName, loadSceneMode, argument);
        }
        
        public static AsyncOperation LoadAsync<T>(T argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        
        {
            return LoadScene<T>(_sceneName, loadSceneMode, argument);
        }
        
        public static void Load<TState, T>(GameStateMachine machine, T argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
            where TState : State<GameStateMachine>
        
        {
            LoadScene<TState, T>(_sceneName, loadSceneMode, machine, argument);
        }
        
        public static AsyncOperation LoadAsync<TState, T>(GameStateMachine machine, T argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
            where TState : State<GameStateMachine>
        
        {
            return LoadScene<TState, T>(_sceneName, loadSceneMode, machine, argument);
        }
        
        public static void Load<TState>(GameStateMachine machine, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
            where TState : State<GameStateMachine>
        {
            LoadScene<TState>(_sceneName, loadSceneMode, machine);
        }
        
        public static AsyncOperation LoadAsync<TState>(GameStateMachine machine, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
            where TState : State<GameStateMachine>
        {
            return LoadScene<TState>(_sceneName, loadSceneMode, machine);
        }
    }
}
